import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from "@/material-tailwind/index";
import { ReduxProvider } from '@/app/_redux/index';
import { LinkHeader } from '@/components/molcules/LinkHeader/index'
import { GoogleTagManager, GoogleAnalytics } from '@next/third-parties/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next.js sample with PokemonAPI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const style = 'max-w-4xl m-auto'
  return (
    <ReduxProvider>
      <ThemeProvider>
        <html lang="en">
          <body className={`${inter.className} ${style}`} >
            <GoogleTagManager gtmId="G-ERMX7KKS11" />
            <GoogleAnalytics gaId="G-ERMX7KKS11" />
            <link
              rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
              integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
              crossOrigin="anonymous"
              referrerPolicy="no-referrer"
            />
            <LinkHeader />
            <div className="mb-6" />
            {children}
          </body>
        </html>
      </ThemeProvider>
    </ReduxProvider>
  )
}
