import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from "@/material-tailwind/index";
import { ReduxProvider } from '@/app/_redux/index';
import { LinkHeader } from '@/components/molcules/LinkHeader/index'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const style = 'max-w-4xl m-auto'
  return (
    <ReduxProvider>
      <ThemeProvider>
        <html lang="en">
          <body className={`${inter.className} ${style}`} >
            <LinkHeader />
            <div className="mb-6" />
            {children}
          </body>
        </html>
      </ThemeProvider>
    </ReduxProvider>
  )
}
